### PR TITLE
Don't precompile any shaders (uber or regular) unless they're going to be used.

### PR DESCRIPTION
**Pull request by jmlee337**
#99 
I'm still trying to figure out what's going on with my problems in #102, but in the meantime, this one actually works

### CODE REVIEW

**Comment by jmlee337** [comment]
this is ready for review

**Comment by Tinob** [comment]
looks good to me, the only thing that can make it better is to force recompilation also when uber shader mode changes, what do you think?

**Comment by jmlee337** [comment]
What do you mean by ubershader mode change? Like exclusive -> hybrid? Or something else?

**Comment by Tinob** [comment]
exactly that, rigth now recompilation is only triguered on  host bits changed but adding ubershader mode to triguer compilation will grant that all  the ubershader will be compiled before using them if the mode changes while gamming.

**Comment by jmlee337** [comment]
Oh I see. I didn't know that was possible haha. I'm not sure how to do that. Is there some settings class I can register a callback with or something?

**Comment by Tinob** [comment]
don't worry i will make thata change is small so  will merge your code and add that later

**Comment by jmlee337** [comment]
sounds good, go ahead and merge

**Pull request merged**
