### PR TITLE
Async Shader Compilation for OpenGL

### PR DESCRIPTION
**Pull request by jmlee337**
OpenGL doesn't have good driver support for parallel shader compilations, so implementing async shader compilation the same way as D3D is not possible. Instead:

- Create a shader compilation thread. 
- Add shader code to be compiled to a queue.
- Consume that queue from the shader compilation thread and compile shaders synchronously.

### CODE REVIEW

**Comment by Tinob** [comment]
what's the difference in performance and stuttering using this method?

**Comment by jmlee337** [comment]
Stuttering is decreased, along with seeing the expected 'pop-in' artifacts. Not sure the best way to measure 'performance' is there an option to log fps data?

Also it was working before but now I'm getting segfaults. Investigating whether I added a typo somewhere or if I have some bug that only occurs in certain conditions

**Comment by jmlee337** [comment]
Going back and building this patch clean stopped the segfaults. I believe the problem is a bad interaction with some setting I was messing with. I'm not sure which setting it was since I remember changing many settings at the same time.

I will go back through one at a time to figure out what setting caused this patch to segfault. Are there any known issues with certain settings producing segfaults already?

**Comment by jmlee337** [comment]
I have not been able to reproduce segfaults since my last comment. I'm chalking it up to bad build artifacts.

I think this PR is ready for review, but can probably hold until your aforementioned next version goes in, as it seems all is not well in the OGL backend atm.

**Comment by Tinob** [comment]
the cause of the worst stuttering while compiling shader syncronously is the overhead for the threaded method you will have to add aoverride that alows compilation on the same threads for some shaders.

**Comment by Tinob** [comment]
latets version fixed a lot of issues so you should rebase your changes

**Comment by jmlee337** [comment]
I actually switched branches, so this can be closed. Continued in #105

**Pull request closed without merging**
